#!/bin/sh

rm -f CMakeCache.txt

# DEBUG
#cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MODULE_PATH=$CMAKE_MODULE_PATH -DCMAKE_INSTALL_PREFIX=$CANARINO_INSTALL_ROOT -G"Eclipse CDT4 - Unix Makefiles" .

# RELEASE
cmake -DCMAKE_INSTALL_PREFIX=$CANARINO_INSTALL_ROOT -DCMAKE_MODULE_PATH=$CMAKE_MODULE_PATH -G"Eclipse CDT4 - Unix Makefiles" .
